---
definitions:

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest # TODO - don't use latest (once we've worked out a policy for third party images)
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))

resources:
  - &git-repo
    name: smokey-repo
    icon: github
    type: git
    source: &git-repo-source
      uri: git@github.com:alphagov/smokey.git
      branch: add-publishing-smoke-test
      private_key: | # pragma: allowlist secret
        ((govukci_private_key))

  - <<: *git-repo
    name: govuk-infrastructure
    source:
      <<: *git-repo-source
      uri: git@github.com:alphagov/govuk-infrastructure.git
      branch: copy-of-add-publishing-smoke-test

  - &docker-image
    name: smokey-image
    type: registry-image
    icon: docker
    source: &docker-image-source
      repository: smokey
      tag: baker-add-publishing-smoke-test
      aws_region: ((concourse-ecr-user_aws-region))
      aws_access_key_id: ((concourse-ecr-user_aws-access-key))
      aws_secret_access_key: ((concourse-ecr-user_aws-secret-access-key))
      aws_role_arn: arn:aws:iam::((aws_production_account_id)):role/push_image_to_ecr_role

  # - &semver-version
  #   name: smokey-version
  #   type: semver
  #   source: &semver-version-source
  #     driver: s3
  #     access_key_id: ((readonly_access_key_id))
  #     secret_access_key: ((readonly_secret_access_key))
  #     session_token: ((readonly_session_token))
  #     bucket: ((readonly_private_bucket_name))
  #     key: smokey-version
  #     region_name: eu-west-2
  #     initial_version: '1.0.0'

jobs:
  - name: update-pipeline
    plan:
    - get: govuk-infrastructure
      trigger: true
    - file: govuk-infrastructure/concourse/pipelines/build-images.yml
      set_pipeline: build-images-baker

  - name: smokey
    plan:
    - in_parallel:
      - get: smokey-repo
        trigger: true
      # - get: smokey-version
      #   params:
      #     bump: minor
      #     pre_without_version: true
      #     pre: release
      - get: govuk-infrastructure
    - task: build-image
      privileged: true
      file: govuk-infrastructure/concourse/tasks/build-image-definition.yml
      input_mapping:
        git-repo: smokey-repo
    - put: smokey-image
      params:
        image: image/image.tar
        # additional_tags: smokey-version/version
    # - in_parallel:
    #   - put: smokey-repo
    #     params:
    #       only_tag: true
    #       tag: smokey-version/version
    #       repository: smokey-repo
    #   - put: smokey-version
    #     params:
    #       file: smokey-version/version
