---
definitions:

resources:
  - name: smokey
    icon: github
    type: git
    source:
      uri: git@github.com:alphagov/smokey.git
      branch: main
      private_key: |
        ((govukci_private_key))

  - name: govuk-infrastructure
    icon: github
    type: git
    source:
      uri: git@github.com:alphagov/govuk-infrastructure.git
      branch: main
      private_key: |
        ((govukci_private_key))

  - name: smokey-image
    type: registry-image
    icon: docker
    source:
      repository: govuk/smokey
      tag: latest
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))

  - name: smokey-version
    type: semver
    source:
      driver: s3
      access_key_id: ((readonly_access_key_id))
      secret_access_key: ((readonly_secret_access_key))
      session_token: ((readonly_session_token))
      bucket: ((readonly_private_bucket_name))
      key: smokey-version
      region_name: eu-west-2
      initial_version: '1.0.0'

jobs:
  - name: update-pipeline
    plan:
    - get: govuk-infrastructure
      trigger: true
    - file: govuk-infrastructure/concourse/pipelines/build-images.yml
      set_pipeline: build-images

  - name: smokey
    plan:
    - in_parallel:
      - get: smokey
        trigger: true
      - get: smokey-version
        params:
          bump: minor
          pre_without_version: true
          pre: release
    - task: build-image
      privileged: true
      params:
        CONTEXT: smokey
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        inputs:
        - name: smokey
        outputs:
        - name: image
        run:
          path: build
    - put: smokey-image
      params:
        image: image/image.tar
        additional_tags: smokey-version/version
    - in_parallel:
      - put: smokey
        params:
          only_tag: true
          tag: smokey-version/version
          repository: smokey
      - put: smokey-version
        params:
          file: smokey-version/version
