---
definitions:

resources:
  - name: daily
    type: time
    icon: clock-outline

  - &git-repo
    name: govuk-infrastructure
    icon: github
    type: git
    source: &git-repo-source
      uri: git@github.com:alphagov/govuk-infrastructure.git
      branch: base_image
      private_key: | # pragma: allowlist secret
        ((govukci_private_key))

  - &docker-image
    name: govuk-ruby-2.7.2-image
    type: registry-image
    icon: docker
    source: &docker-image-source
      repository: govuk-ruby-2.7.2
      tag: latest
      aws_region: ((concourse-ecr-user_aws-region))
      aws_access_key_id: ((concourse-ecr-user_aws-access-key))
      aws_secret_access_key: ((concourse-ecr-user_aws-secret-access-key))
      aws_role_arn:
        "arn:aws:iam::((aws_production_account_id)):role\
        /push_image_to_ecr_role"

  - <<: *docker-image
    name: govuk-ruby-2.7.3-image
    source:
      <<: *docker-image-source
      repository: govuk-ruby-2.7.3

  - <<: *docker-image
    name: govuk-ruby-2.6.6-image
    source:
      <<: *docker-image-source
      repository: govuk-ruby-2.6.6

  - &semver-version
    name: govuk-ruby-2.7.2-version
    type: semver
    source: &semver-version-source
      driver: s3
      access_key_id: ((readonly_access_key_id))
      secret_access_key: ((readonly_secret_access_key))
      session_token: ((readonly_session_token))
      bucket: ((readonly_private_bucket_name))
      key: govuk-ruby-2.7.2-version
      region_name: eu-west-2
      initial_version: '1.0.0'

  - <<: *semver-version
    name: govuk-ruby-2.7.3-version
    source:
      <<: *semver-version-source
      key: govuk-ruby-2.7.3-version

  - <<: *semver-version
    name: govuk-ruby-2.6.6-version
    source:
      <<: *semver-version-source
      key: govuk-ruby-2.6.6-version

  - &s3-file
    name: govuk-ruby-2.7.2-file
    type: s3
    icon: file
    source: &s3-file-source
      bucket: ((readonly_private_bucket_name))
      access_key_id: ((readonly_access_key_id))
      secret_access_key: ((readonly_secret_access_key))
      session_token: ((readonly_session_token))
      region_name: eu-west-2
      versioned_file: govuk-ruby-2.7.2-file
      initial_version: "0"
      disable_multipart: true

  - <<: *s3-file
    name: govuk-ruby-2.7.3-file
    source:
      <<: *s3-file-source
      versioned_file: govuk-ruby-2.7.3-file

  - <<: *s3-file
    name: govuk-ruby-2.6.6-file
    source:
      <<: *s3-file-source
      versioned_file: govuk-ruby-2.6.6-file


jobs:

  - name: govuk-ruby-2.7.2
    plan:
      - in_parallel:
          - get: daily
            trigger: true
          - get: govuk-infrastructure
          - get: govuk-ruby-2.7.2-image
      - task: build-image
        privileged: true
        file: govuk-infrastructure/concourse/tasks/build-image-definition.yml
        input_mapping:
          git-repo: govuk-infrastructure
        params:
          DOCKERFILE: git-repo/docker/images/govuk-ruby/2.7.2/buster/Dockerfile
          UNPACK_ROOTFS: true
        output_mapping:
          image: built_image
      - task: get-status-built
        privileged: true
        image: built_image
        config:
          platform: linux
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Get a hash of the packages list"
                dpkg -l | shasum | awk '{print $1}' > status-built/status-built
          outputs:
            - name: status-built
      - task: get-status-latest
        privileged: true
        image: govuk-ruby-2.7.2-image
        config:
          platform: linux
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Get a hash of the packages list"
                dpkg -l | shasum | awk '{print $1}' > \
                status-latest/status-latest
          outputs:
            - name: status-latest
      - task: compare_status
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 'latest'
          inputs:
            - name: status-built
            - name: status-latest
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Compare package lists between built image and latest,\
                 if identical we don't need to push a new image to ECR"
                ! diff ./status-built/status-built ./status-latest/status-latest
        on_success:
          do:
            - put: govuk-ruby-2.7.2-file
              params:
                file: built_image/image.tar

  - name: push_govuk-ruby-2.7.2
    plan:
      - in_parallel:
          - get: govuk-ruby-2.7.2-file
            trigger: true
            passed:
              - govuk-ruby-2.7.2
          - get: govuk-ruby-2.7.2-image
      - task: push-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 'latest'
          inputs:
            - name: built_image
          run:
            path: "echo"
            args: ["Pushing new image to ECR"]
          outputs:
            - name: built_image
        on_success:
          do:
            - get: govuk-ruby-2.7.2-version
              params:
                bump: minor
                pre_without_version: true
                pre: release
            - put: govuk-ruby-2.7.2-image
              params:
                image: built_image/govuk-ruby-2.7.2-file
                additional_tags: govuk-ruby-2.7.2-version/version
            - put: govuk-ruby-2.7.2-version
              params:
                bump: minor
                pre_without_version: true
                pre: release
        input_mapping:
          built_image: govuk-ruby-2.7.2-file

  - name: govuk-ruby-2.7.3
    plan:
      - in_parallel:
          - get: daily
            trigger: true
          - get: govuk-infrastructure
          - get: govuk-ruby-2.7.3-image
      - task: build-image
        privileged: true
        file: govuk-infrastructure/concourse/tasks/build-image-definition.yml
        input_mapping:
          git-repo: govuk-infrastructure
        params:
          DOCKERFILE: git-repo/docker/images/govuk-ruby/2.7.3/buster/Dockerfile
          UNPACK_ROOTFS: true
        output_mapping:
          image: built_image
      - task: get-status-built
        privileged: true
        image: built_image
        config:
          platform: linux
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Get a hash of the packages list"
                dpkg -l | shasum | awk '{print $1}' > status-built/status-built
          outputs:
            - name: status-built
      - task: get-status-latest
        privileged: true
        image: govuk-ruby-2.7.3-image
        config:
          platform: linux
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Get a hash of the packages list"
                dpkg -l | shasum | awk '{print $1}' > \
                status-latest/status-latest
          outputs:
            - name: status-latest
      - task: compare_status
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 'latest'
          inputs:
            - name: status-built
            - name: status-latest
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Compare package lists between built image and latest,\
                      if identical we don't need to push a new image to ECR"
                ! diff ./status-built/status-built ./status-latest/status-latest
        on_success:
          do:
            - put: govuk-ruby-2.7.3-file
              params:
                file: built_image/image.tar

  - name: push_govuk-ruby-2.7.3
    plan:
      - in_parallel:
          - get: govuk-ruby-2.7.3-file
            trigger: true
            passed:
              - govuk-ruby-2.7.3
          - get: govuk-ruby-2.7.3-image
      - task: push-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 'latest'
          inputs:
            - name: built_image
          run:
            path: "echo"
            args: ["Pushing new image to ECR"]
          outputs:
            - name: built_image
        on_success:
          do:
            - get: govuk-ruby-2.7.3-version
              params:
                bump: minor
                pre_without_version: true
                pre: release
            - put: govuk-ruby-2.7.3-image
              params:
                image: built_image/govuk-ruby-2.7.3-file
                additional_tags: govuk-ruby-2.7.3-version/version
            - put: govuk-ruby-2.7.3-version
              params:
                bump: minor
                pre_without_version: true
                pre: release
        input_mapping:
          built_image: govuk-ruby-2.7.3-file

  - name: govuk-ruby-2.6.6
    plan:
      - in_parallel:
          - get: daily
            trigger: true
          - get: govuk-infrastructure
          - get: govuk-ruby-2.6.6-image
      - task: build-image
        privileged: true
        file: govuk-infrastructure/concourse/tasks/build-image-definition.yml
        input_mapping:
          git-repo: govuk-infrastructure
        params:
          DOCKERFILE: git-repo/docker/images/govuk-ruby/2.6.6/buster/Dockerfile
          UNPACK_ROOTFS: true
        output_mapping:
          image: built_image
      - task: get-status-built
        privileged: true
        image: built_image
        config:
          platform: linux
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Get a hash of the packages list"
                dpkg -l | shasum | awk '{print $1}' > status-built/status-built
          outputs:
            - name: status-built
      - task: get-status-latest
        privileged: true
        image: govuk-ruby-2.6.6-image
        config:
          platform: linux
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Get a hash of the packages list"
                dpkg -l | shasum | awk '{print $1}' > \
                status-latest/status-latest
          outputs:
            - name: status-latest
      - task: compare_status
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 'latest'
          inputs:
            - name: status-built
            - name: status-latest
          run:
            path: "sh"
            args:
              - -cx
              - |
                echo "Compare package lists between built image and latest,\
                 if identical we don't need to push a new image to ECR"
                ! diff ./status-built/status-built ./status-latest/status-latest
        on_success:
          do:
            - put: govuk-ruby-2.6.6-file
              params:
                file: built_image/image.tar


  - name: push_govuk-ruby-2.6.6
    plan:
      - in_parallel:
          - get: govuk-ruby-2.6.6-file
            trigger: true
            passed:
              - govuk-ruby-2.6.6
          - get: govuk-ruby-2.6.6-image
      - task: push-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: 'latest'
          inputs:
            - name: built_image
          run:
            path: "echo"
            args: ["Pushing new image to ECR"]
          outputs:
            - name: built_image
        on_success:
          do:
            - get: govuk-ruby-2.6.6-version
              params:
                bump: minor
                pre_without_version: true
                pre: release
            - put: govuk-ruby-2.6.6-image
              params:
                image: built_image/govuk-ruby-2.6.6-file
                additional_tags: govuk-ruby-2.6.6-version/version
            - put: govuk-ruby-2.6.6-version
              params:
                bump: minor
                pre_without_version: true
                pre: release
        input_mapping:
          built_image: govuk-ruby-2.6.6-file
