---
definitions:

resource_types:
  - name: github-commit
    type: registry-image
    source:
      repository: govuk/github-commit
      tag: 0.1.0

resources:
  - name: govuk-infrastructure-commit
    type: github-commit
    icon: github
    source:
      # Will fetch commits from *any* branch
      repository: alphagov/govuk-infrastructure
      access_token: ((github_access_token))
      path: govuk-infrastructure-commit

  - icon: github
    name: govuk-infrastructure
    source:
      branch: ((govuk_infrastructure_branch))
      uri: https://github.com/alphagov/govuk-infrastructure
    type: git

jobs:
  - name: update-pipeline
    plan:
    - get: govuk-infrastructure
      trigger: true
    - file: govuk-infrastructure/concourse/pipelines/ci.yml
      set_pipeline: ci-govuk-infrastructure-main
      var_files:
        - govuk-infrastructure/concourse/parameters/ci/ci.yml

  - name: terraform-cluster-infrastructure
    plan:
    - get: govuk-infrastructure-commit
      trigger: true
    - put: govuk-infrastructure-commit
      params: {status: pending, context: terraform-plan-cluster-infrastructure}
    - task: terraform-cluster
      config: &terraform-cluster-config
        inputs:
        - name: govuk-infrastructure-commit
        params: &terraform-cluster-params
          ASSUME_ROLE_ARN: ((concourse_ci_role_arn))
          AWS_REGION: ((aws_region))
          DEPLOYMENT_PATH: govuk-infrastructure-commit/repo/terraform/deployments/cluster-infrastructure
          ENVIRONMENT: ((govuk_environment))
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: digiticketsgroup/terraforming
            tag: tf-1.0.1-aws-2.2.18-jq-1.5-git-2.32.0 #TODO: build our own image instead.
            username: ((docker_hub_username))
            password: ((docker_hub_authtoken))
        run:
          path: govuk-infrastructure-commit/repo/concourse/tasks/terraform.sh
          args: ["plan", "-lock=false", "-refresh=false"]
      on_success:
        put: govuk-infrastructure-commit
        params: {status: success, context: terraform-plan-cluster-infrastructure}
      on_failure:
        put: govuk-infrastructure-commit
        params: {status: failure, context: terraform-plan-cluster-infrastructure}
      on_abort:
        put: govuk-infrastructure-commit
        params: {status: error, context: terraform-plan-cluster-infrastructure}
      on_error:
        put: govuk-infrastructure-commit
        params: {status: error, context: terraform-plan-cluster-infrastructure}

  - name: terraform-cluster-services
    plan:
    - get: govuk-infrastructure-commit
      trigger: true
    - put: govuk-infrastructure-commit
      params: {status: pending, context: terraform-plan-cluster-services}
    - task: terraform-cluster-addons
      config:
        <<: *terraform-cluster-config
        params:
          <<: *terraform-cluster-params
          DEPLOYMENT_PATH: govuk-infrastructure-commit/repo/terraform/deployments/cluster-services
      on_success:
        put: govuk-infrastructure-commit
        params: {status: success, context: terraform-plan-cluster-services}
      on_failure:
        put: govuk-infrastructure-commit
        params: {status: failure, context: terraform-plan-cluster-services}
      on_abort:
        put: govuk-infrastructure-commit
        params: {status: error, context: terraform-plan-cluster-services}
      on_error:
        put: govuk-infrastructure-commit
        params: {status: error, context: terraform-plan-cluster-services}
