---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest # TODO - don't use latest (once we've worked out a policy for third party images)
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))

  - name: registry-image
    type: docker-image
    source:
      repository: govuk/registry-image
      tag: f0.0.1
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))

resources:
  - icon: github
    name: govuk-infrastructure
    source:
      branch: ((govuk_infrastructure_branch))
      uri: https://github.com/alphagov/govuk-infrastructure
    type: git

  - name: deploy-slack-channel
    type: slack-notification
    icon: bell-ring
    source:
      url: https://hooks.slack.com/services/((deploy_apps_slack_webhook))
      disable: ((disable_slack_channel_alerts))

jobs:
  - name: update-pipeline
    plan:
    - get: govuk-infrastructure
      trigger: true
    - file: govuk-infrastructure/concourse/pipelines/eks.yml
      set_pipeline: self
      var_files:
        - govuk-infrastructure/concourse/parameters/((govuk_environment))/eks.yml

  - name: terraform-cluster-infrastructure
    plan:
    - get: govuk-infrastructure
      trigger: true
      passed:
      - update-pipeline
    - task: terraform-apply
      config: &terraform-apply-config
        inputs:
        - name: govuk-infrastructure
        params: &terraform-apply-params
          ASSUME_ROLE_ARN: ((concourse_deployer_role_arn))
          AWS_REGION: ((aws_region))
          DEPLOYMENT_PATH: govuk-infrastructure/terraform/deployments/cluster-infrastructure
          ENVIRONMENT: ((govuk_environment))
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: govuk-terraform
            aws_region: eu-west-1
            aws_ecr_registry_id: ((ecr_registry_id))
            aws_ec2_credentials: true
            variant: release
            aws_role_arns:
              - ((concourse_deployer_role_arn))
              - ((concourse_ecr_role_arn))
        run:
          path: govuk-infrastructure/concourse/tasks/terraform.sh
          args: ["apply"]
    on_failure: &notify-slack-failure
      put: deploy-slack-channel
      params:
        channel: "#govuk-deploy-alerts" # TODO: Alert owner Slack channels in future
        username: ((govuk_environment)) $BUILD_JOB_NAME
        icon_emoji: ":concourse:"
        silent: true
        text: |
          :red_circle: Failed deploy: https://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: terraform-govuk-publishing-infrastructure
    plan:
    - get: govuk-infrastructure
      trigger: true
    - task: terraform-apply
      config:
        <<: *terraform-apply-config
        params:
          <<: *terraform-apply-params
          DEPLOYMENT_PATH: govuk-infrastructure/terraform/deployments/govuk-publishing-infrastructure
    on_failure:
      <<: *notify-slack-failure

  - name: terraform-cluster-services
    plan:
    - get: govuk-infrastructure
      trigger: true
      passed:
      - terraform-cluster-infrastructure
      - terraform-govuk-publishing-infrastructure
    - task: terraform-apply
      config:
        <<: *terraform-apply-config
        params:
          <<: *terraform-apply-params
          DEPLOYMENT_PATH: govuk-infrastructure/terraform/deployments/cluster-services
    on_failure:
      <<: *notify-slack-failure
