name: 'Setup Node'
description: 'Install Node and yarn dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: lts/*
        cache: 'yarn'

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install --frozen-lockfile
