name: 'Setup Node'
description: 'Install Node and yarn dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install --frozen-lockfile
