name: 'Setup Node'
description: 'Install Node and yarn dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install --frozen-lockfile
