name: 'Setup Node'
description: 'Install Node and yarn dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
      with:
        node-version: lts/*
        cache: 'yarn'

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install --frozen-lockfile
