name: 'Setup Node'
description: 'Install Node and JavaScript dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install --frozen-lockfile
