name: 'Setup Node'
description: 'Install Node and yarn dependencies'
runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: lts/*
        cache: 'yarn'

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install --immutable
