apiVersion: v1
data:
  logstash-nginx.config: |
    input {
      http {
        port => 8080
        ssl_enabled => false
      }
    }

    filter {
      json {
        source => "message"
      }
      useragent {
        source => "agent"
        target => "useragent"
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "nginx"
        ssl_verification_mode => "none"
      }
      stdout {
        codec => rubydebug
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: logstash
  name: logstash-nginx-config
  namespace: elk
