apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: elk
data:
  fluentbit-config: |
    service:
      flush: 1
      log_level: info

    pipeline:
      inputs:
        - name: kubernetes_events
          tag: k8s_events
          db: /mnt/k8s-events/k8s-events.db
      outputs:
        - name: stdout
          match: '*'
        - name: opensearch
          match: '*'
          host: elasticsearch
          port: 9200
          index: k8s-events
          http_user: 'fluentbit'
          http_passwd: "${ELASTICSEARCH_PASSWORD}"
          suppress_type_name: true
