apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: elk
data:
  fluentbit-config: |
    service:
      flush: 1
      log_level: info

    pipeline:
      inputs:
        - name: kubernetes_events
          tag: k8s_events
          db: /mnt/k8s-events/k8s-events.db
      outputs:
        - name: stdout
          match: '*'
        - name: opensearch
          match: '*'
          host: elasticsearch
          port: 9200
          index: k8s-events
          http_user: 'fluentbit'
          http_passwd: "${ELASTICSEARCH_PASSWORD}"
          suppress_type_name: true




#     extensions:
#       basicauth/logs:
#         client_auth:
#           username: 'fluentbit'
#           password: 
#     receivers:
#       k8sobjects:
#         objects:
#           - name: events
#             mode: watch
#             group: events.k8s.io/v1
# 
#     processors:
#       transform:
#         log_statements:
#           - statements:
#             - set(log.time, Time(log.body["object"]["lastTimestamp"], "2006-01-02T15:04:05Z"))
#             - set(log.cache["object"], log.body["object"])
#             - delete_key(log.body, "object")
#             - merge_maps(log.body, log.cache["object"], "upsert")
#     exporters:
#       debug:
#         verbosity: detailed
#       opensearch:
#         logs_index: k8s-events
#         http:
#           endpoint: http://elasticsearch:9200
#           auth:
#             authenticator: basicauth/logs
#         mapping:
#           mode: ecs
#           dedot: true
#     service:
#       extensions:
#        - basicauth/logs
#       pipelines:
#         logs:
#           receivers: [k8sobjects]
#           processors: [transform]
#           exporters:
#             - debug
#             - opensearch
# 
