name: "Report GitHub workflow run failure to Slack"
description: "Report Github run failure to a nominated slack channel"
inputs:
  slack_webhook_url:
    description: "Slack webhook URL"
    required: true
  channel:
    description: "Name of the channel to send failure notifications to"
    required: true
  message:
    description: "Optional, custom message that can be included in the notification"
    default: ""
runs:
  using: "composite"
  steps:
    - if:  ${{ github.ref_name == 'main' }}
      run: |
        # run checks as github actions required is not being enforced - https://github.com/actions/runner/issues/1070
        [[ "${{ inputs.slack_webhook_url }}" ]] || { echo "slack_webhook_url input is empty" ; exit 1; }
        [[ "${{ inputs.channel }}" ]] || { echo "channel input is empty" ; exit 1; }
      shell: bash
    - if:  ${{ github.ref_name == 'main' }}
      name: Send slack message
      uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
      with:
        errors: true
        webhook: ${{ inputs.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "channel": "${{ inputs.channel }}",
            "text": "The <https://github.com/${{ github.repository }}> Github run failed.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "The <https://github.com/${{ github.repository }}> failed on ${{ github.ref_name }}.\n${{ inputs.message }}",
                },
                "accessory": {
                  "type": "button",
                  "text": {
                      "type": "plain_text",
                      "text": "Check the build logs"
                  },
                  "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "action_id": "button-view-workflow"
                }
              }
            ]
          }
