# Configure serving configs.
#
# Each key in this file represents the ID and displayName of a serving config.
#
# IMPORTANT: The ID needs to be between 1-63 characters and *unique both within this file and
# amongst all serving configs*! Stay consistent by using `search_` as the prefix for any serving config added
# in this file.
#
# see https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1alpha/projects.locations.collections.engines.servingConfigs


search_raw:
  boostControlIds: []
  synonymsControlIds: []
