# Default values for static.

govukEnvironment: test
govukStack: pink
govukDomainExternal: govuk.digital
govukDomainInternal: govuk-internal.digital
clusterDomain: svc.cluster.local

service:
  type: NodePort
  annotations: {}
  port: 80

replicaCount: 1

appImage:
  repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/static
  pullPolicy: IfNotPresent
  tag: latest

nginxImage:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

appPort: 3000
nginxPort: 80

resources: {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## See template file for how application conatiner env default value is computed
appGovukAppDomain:
appGovukDomainExternal:
appGovukAppName:
appGovukWebsiteRoot:
appDefaultTtl: "1800"
appGovukAssetRoot:
appRedisUrl:
appGovukAppRoot: "/var/apps/static"
appGovukAppType: "rack"

## Extra environment variables to attach to application container
##
# appExtraEnv:
#   - name: hello
#     value: world
