---
apiVersion: v1
kind: Service
metadata:
  name: static
spec:
  type: NodePort
  selector:
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/static@sha256:08c32c52ea59862893287a6701a0f24db2c792aa36f28036122f3462bd8520f9
        ports:
        - containerPort: 80
        env:
          - name: ASSET_HOST
            value: "https://www-origin.fred.eks.test.govuk.digital"
          - name: DEFAULT_TTL
            value: "1800"
          - name: GOVUK_APP_DOMAIN
            value: "default.svc.cluster.local"
          - name: GOVUK_APP_DOMAIN_EXTERNAL
            value: "fred.eks.test.govuk.digital"
          - name: GOVUK_APP_NAME
            value: "static"
          - name: GOVUK_APP_ROOT
            value: "/var/apps/static"
          - name: GOVUK_APP_TYPE
            value: "rack"
          - name: GOVUK_ENVIRONMENT
            value: "test"
          - name: GOVUK_WEBSITE_ROOT
            value: "https://www.fred.eks.test.govuk.digital"
          - name: GOVUK_WORKSPACE
            value: "fred"
          - name: REDIS_URL
            value: "redis://redis.fred.test.govuk-internal.digital:6379"
          - name: PORT
            value: "80"
          - name: RAILS_ENV
            value: "production"
          - name: SENTRY_ENVIRONMENT
            value: "test-ecsplatform-ecs"
          - name: UNICORN_WORKER_PROCESSES
            value: "12"
          - name: SECRET_KEY_BASE
            value: "123456789"
