---
apiVersion: v1
kind: Service
metadata:
  name: content-store
spec:
  type: NodePort
  selector:
    app: content-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-store
  labels:
    app: content-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-store
  template:
    metadata:
      labels:
        app: content-store
    spec:
      containers:
      - name: content-store
        image: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/content-store:bill-content-schemas
        ports:
        - containerPort: 80
        env:
          - name: DEFAULT_TTL
            value: "1800"
          - name: GOVUK_APP_DOMAIN
            value: "default.svc.cluster.local"
          - name: GOVUK_APP_DOMAIN_EXTERNAL
            value: "fred.eks.test.govuk.digital"
          - name: GOVUK_APP_NAME
            value: "content-store"
          - name: GOVUK_APP_TYPE
            value: "rack"
          - name: GOVUK_CONTENT_SCHEMAS_PATH
            value: "/govuk-content-schemas"
          - name: GOVUK_ENVIRONMENT
            value: "test"
          - name: GOVUK_WEBSITE_ROOT
            value: "https://www.fred.eks.test.govuk.digital"
          - name: GOVUK_WORKSPACE
            value: "fred"
          - name: MONGODB_URI
            value: "mongodb://mongo-1.pink.test.govuk-internal.digital,mongo-2.pink.test.govuk-internal.digital,mongo-3.pink.test.govuk-internal.digital/content_store_production"
          - name: PLEK_SERVICE_PUBLISHING_API_URI
            value: "http://publishing-api-web.default.svc.cluster.local"
          - name: PLEK_SERVICE_ROUTER_API_URI
            value: "http://router-api.default.svc.cluster.local"
          - name: PLEK_SERVICE_SIGNON_URI
            value: "https://signon.fred.eks.test.govuk.digital"
          - name: PORT
            value: "80"
          - name: RAILS_ENV
            value: "production"
          - name: SENTRY_ENVIRONMENT
            value: "test-ecsplatform-ecs"
          - name: UNICORN_WORKER_PROCESSES
            value: "12"
          - name: SECRET_KEY_BASE
            value: "123456789"
