apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ephemeral-cluster-validator
  name: ephemeral-cluster-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-cluster-validator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ephemeral-cluster-validator
    spec:
      containers:
      - image: "nginxinc/nginx-unprivileged:latest"
        name: nginx
        resources: {}
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: ephemeral-cluster-validator-tmp
            mountPath: /tmp
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 101
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      volumes:
      - name: ephemeral-cluster-validator-tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ephemeral-cluster-validator
  name: ephemeral-cluster-validator
spec:
  ports:
  - name: 443-8080
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: ephemeral-cluster-validator
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: ephemeral-cluster-validator
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:430354129336:certificate/539c42e5-4194-4213-83a2-a68620c6e18a"
    external-dns.alpha.kubernetes.io/hostname: ephemeral-cluster-validator.eph-20250617.ephemeral.govuk.digital
spec:
  ingressClassName: aws-alb
  defaultBackend:
    service:
      name: ephemeral-cluster-validator
      port:
        number: 443
