name: 'Setup Postgres'
description: 'Create a new Postgres database'
outputs:
  db-url:
    description: "The URL to connect to the database"
    value: ${{ steps.generate-url.outputs.db-url }}
runs:
  using: "composite"
  steps:
    - name: Start container
      id: start-container
      env:
        POSTGRES_IMAGE_TAG: 13-alpine
        POSTGRES_PORT: 5432
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: test
      shell: bash
      run: |
        docker run --name postgres \
         --rm --detach \
         --publish "${POSTGRES_PORT}:${POSTGRES_PORT}" \
         --env "POSTGRES_USER=${POSTGRES_USER}" \
         --env "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" \
         --env "POSTGRES_DB=${POSTGRES_DB}" \
         postgres:${POSTGRES_IMAGE_TAG}

    - name: Generate database URL
      id: generate-url
      env:
        POSTGRES_PORT: 5432
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: test
      shell: bash
      run: echo "db-url=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB}" >> $GITHUB_OUTPUT
