apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  ASSETS_PREFIX: "{{ .Values.appAssetsPrefix }}"
  BASIC_AUTH_USERNAME: "{{ .Values.appBasicAuthUsername }}"
  DEFAULT_TTL: "{{ .Values.appDefaultTtl }}"
  EMAIL_GROUP_BUSINESS: "{{ .Values.appEmailGroupBusiness }}"
  EMAIL_GROUP_CITIZEN: "{{ .Values.appEmailGroupCitizen }}"
  EMAIL_GROUP_FORCE_PUBLISH_ALERTS: "{{ .Values.appEmailGroupForcePublishAlerts }}"
  FACT_CHECK_SUBJECT_PREFIX: "{{ .Values.appFactCheckSubjectPrefix }}"
  FACT_CHECK_USERNAME: "{{ .Values.appFactCheckUsername }}"
  GOVUK_APP_DOMAIN: "{{ .Values.appGovukAppDomain | default (printf "%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.clusterDomain) }}"
  GOVUK_APP_DOMAIN_EXTERNAL: "{{ .Values.appGovukDomainExternal | default (printf "%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
  GOVUK_APP_NAME: "{{ .Values.appGovukAppName | default .Release.Name }}"
  GOVUK_APP_ROOT: "{{ .Values.appGovukAppRoot }}"
  GOVUK_APP_TYPE: "{{ .Values.appGovukAppType }}"
  GOVUK_ASSET_ROOT: "{{ .Values.appGovukAssetRoot | default (printf "https://assets.%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
  ASSET_HOST: "{{ .Values.appAssetHost | default (printf "https://www-origin.%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
  GOVUK_ENVIRONMENT: "{{ .Values.govukEnvironment }}"
  GOVUK_WEBSITE_ROOT: "{{ .Values.appGovukWebsiteRoot | default (printf "https://www-origin.%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
  PLEK_SERVICE_CONTENT_STORE_URI: "{{ .Values.appPlekServiceContentStoreUri | default (printf "http://content-store.%s.%s" .Release.Namespace .Values.clusterDomain) }}"
  PLEK_SERVICE_DRAFT_ORIGIN_URI: "{{ .Values.appPlekServiceContentStoreUri | default (printf "https://draft-origin.%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
  PLEK_SERVICE_PUBLISHING_API_URI: "{{ .Values.appPlekServicePublishingApiUri | default (printf "http://publishing-api-web.%s.%s" .Release.Namespace .Values.clusterDomain) }}"
  PLEK_SERVICE_SIGNON_URI: "{{ .Values.appPlekServiceSignonUri | default (printf "https://signon.%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
  PLEK_SERVICE_STATIC_URI: "{{ .Values.appPlekServiceStaticUri | default (printf "http://static.%s.%s" .Release.Namespace .Values.clusterDomain) }}"
  PORT: "{{ .Values.appPort }}"
  RAILS_ENV: "{{ .Values.appRailsEnv }}"
  REDIS_URL: "{{ .Values.appRedisUrl }}"    # TODO: decide on Redis for EKS
