---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  dataFrom:
    - key: "{{ .Values.secretsPrefix }}{{ .Release.Name }}"
