apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.className }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: {{ .Values.controller }}
