google_cloud_folder          = "278098142879"
google_cloud_billing_account = "015C7A-FAF970-B0D375"
project_id                   = "govuk-knowledge-graph-staging"
name                         = "staging"
access_group_name            = "govuk-gcp-access"
environment_workspace_name   = "govuk-knowledge-graph-staging"
tfc_project_name             = "govuk-data-engineering"