google_cloud_folder          = "278098142879"
google_cloud_billing_account = "015C7A-FAF970-B0D375"
project_id                   = "govuk-knowledge-graph-dev"
name                         = "dev"
access_group_name            = "govuk-gcp-access-dev"
environment_workspace_name   = "govuk-knowledge-graph-dev"
tfc_project_name             = "govuk-data-engineering"