additionalPrometheusRulesMap:
  rule-name: 
    groups:
    - name: CoreAlerts
      rules:
      - alert: RouterHttpRequestErrorRate
        expr: sum(rate(promhttp_metric_handler_requests_total{code=~"^5..", job="apps/router"}[5m])) / sum(rate(promhttp_metric_handler_requests_total{job="apps/router"}[5m])) > 0.1
        for: 10m
        labels:
            severity: critical
        annotations:
            summary: "High error rate for apps/router"
            description: "apps/router has high error rate for more than 10 minutes."
