resource "aws_s3_bucket" "publisher_csvs" {
  bucket        = "govuk-${var.govuk_environment}-publisher-csvs"
  force_destroy = var.force_destroy
  tags = {
    Product     = "GOV.UK"
    System      = "Publisher"
    Service     = "Publisher S3 Bucket"
    Environment = "${var.govuk_environment}"
    Owner       = "govuk-replatforming-team@digital.cabinet-office.gov.uk"
    Name        = "CSVs generated by Publisher in ${var.govuk_environment}"
  }
}
