resource "aws_s3_bucket" "publisher_csvs" {
  bucket        = "govuk-${var.govuk_environment}-publisher-csvs"
  force_destroy = var.force_destroy
  tags = {
    Name        = "CSVs generated by Publisher in ${var.govuk_environment}"
    Environment = var.govuk_environment
  }
}
