resource "aws_s3_bucket" "publisher_csvs" {
  bucket        = "govuk-${var.govuk_environment}-publisher-csvs"
  force_destroy = var.force_destroy
  tags = {
    System = "Publisher"
    Name   = "CSVs generated by Publisher"
    Owner  = "#govuk-publishing-platform"
  }
}
