#========================================================================================
# This Dockerfile creates a container image with the dependencies required
# to deploy
# This is needed for running the deploy scripts in a container environment like Concourse.
#========================================================================================
FROM governmentpaas/awscli:latest

# TODO: Install AWS CLI, replace governmentpaas/awscli:latest
# TODO: Install terraform
# TODO: use bash

ENTRYPOINT ["/bin/ash"]
