apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.webReplicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
      annotations:
        # TODO: if Helm library is used, `$.Template.BasePath` needs to be replaced
        # by chart name, see https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/configmap: {{ include (print $.Template.BasePath "/common/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
          command: ["foreman"]
          args: ["run", "web"]
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
          env:
          {{- range .Values.secrets }}
            - name: {{ . | title }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: {{ . | title }}
          {{- end }}
          {{- with .Values.webExtraEnv }}
            {{- . | toYaml | trim | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.webResources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthcheck/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
        - name: nginx
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.nginxPort }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
          - name: {{ .Release.Name }}-web-nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
      - name: {{ .Release.Name }}-web-nginx-conf
        configMap:
          name: {{ .Release.Name }}-web-nginx-conf
