---
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: jobrequestoperatorrequiredannotations
  annotations:
    metadata.gatekeeper.sh/title: Validate a JobRequest has a requested-by annotation
    description: This constraint ensures a JobRequest has the requested-by annotation
spec:
  crd:
    spec:
      names:
        kind: JobRequestOperatorRequiredAnnotations

  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
        - engine: Rego
          source:
            version: "v1"
            rego: |
              package jobrequestoperatorrequiredannotations

              valid_operation if {
                input.review.operation != "DELETE"
              }

              annotation_keys := {
                "JobRequest": "platform.publishing.service.gov.uk/requested-by",
                "JobRequestReview": "platform.publishing.service.gov.uk/reviewed-by"
              }

              violation contains {"msg": msg} if {
                valid_operation

                annotation_key := annotation_keys[input.review.kind.kind]

                annotation_value := object.get(
                  input.review.object,
                  ["metadata", "annotations", annotation_key],
                  ""
                )
                annotation_value == ""

                msg := sprintf(
                  "The %s (%s) does not include the required annotation (%s)",
                  [input.review.kind.kind, input.review.name, annotation_key]
                )
              }

              default parse_gds_username(gds_users_part) := ""

              parse_gds_username(gds_users_part) := username if {
                strings.any_suffix_match(gds_users_part, [
                  "-fulladmin",
                  "-tempadmin",
                  "-platformengineer",
                  "-developer",
                  "-readonly",
                  "-ithctester",
                ])
                user_parts := split(gds_users_part, "-")
                username = concat("-", array.slice(user_parts, 0, count(user_parts) - 1))
              }

              parse_entraid_username(entra_id_part, gds_username) := entra_id_part if {
                contains(entra_id_part, "@")
              } else := gds_username

              default parse_username_from_arn(arn) := ""

              parse_username_from_arn(arn) := username if {
                arn_parts := split(arn, "/")
                arn_parts_length := count(arn_parts)
                arn_parts_length == 3

                arn_prefix := arn_parts[0]

                endswith(arn_prefix, "assumed-role")

                gds_username := parse_gds_username(arn_parts[1])
                username := parse_entraid_username(arn_parts[2], gds_username)
              }

              violation contains {"msg": msg} if {
                valid_operation

                annotation_key := annotation_keys[input.review.kind.kind]
                arn := input.review.object.metadata.annotations[annotation_key]

                username := parse_username_from_arn(arn)

                username == ""

                msg := sprintf(
                  "%s (%s) has a %s annotation (%s) which cannot be parsed to a username",
                  [input.review.kind.kind, input.review.name, split(annotation_key, "/")[1], arn]
                )
              }

              violation contains {"msg": msg} if {
                valid_operation
                input.review.kind.kind == "JobRequestReview"

                namespace := input.review.namespace
                job_request_name := input.review.object.spec.jobRequestName

                job_request := data.inventory.namespace[namespace]["platform.publishing.service.gov.uk/v1"]["JobRequest"][job_request_name]

                requested_by_arn := input.review.object.metadata.annotations[annotation_keys["JobRequestReview"]]
                reviewed_by_arn := job_request.metadata.annotations[annotation_keys["JobRequest"]]

                requested_by_username := parse_username_from_arn(requested_by_arn)
                reviewed_by_username := parse_username_from_arn(reviewed_by_arn)

                requested_by_username == reviewed_by_username

                msg := sprintf(
                  "JobRequestReview (%s) cannot review JobRequest (%s) since the reviewer and requester are the same user (%s)",
                  [input.review.name, job_request_name, reviewed_by_username]
                )
              }
