filter {
  if [message] =~ /^{.*}/ {
    json {
      source => "message"
      target => "logjson"
      skip_on_invalid_json => true
    }
  }

  # Extract Sidekiq message (e.g. "start")
  if [logjson][message] {
    mutate {
      rename => { "[logjson][message]" => "[logjson_message]" }
    }
  }

  # Detect nested Sidekiq objects and extract to separate field
  if [logjson_message] and [logjson_message][queues] {
    mutate {
      rename => { "[logjson_message]" => "[logjson_sidekiq_object]" }
    }
  }

  # Fix email-alert-frontend errors landing in the DLQ
  if [logjson][status] and [logjson][status] =~ /[^0-9.-]/ {
    mutate {
      rename => { "[logjson][status]" => "[logjson][status_text]" }
    }
  }

  useragent {
    source => "[logjson][http_user_agent]"
    ecs_compatibility => "v8"
  }

  mutate {
    copy => {"[logjson][upstream_response_time]" => "upstream_response_time_float"}
    convert => {"upstream_response_time_float" => "float"}
  }

  # If error is a string and not an object (fixes mirror?)
  if [error] and ![error][message] and ![error][type] {
    mutate {
      rename => { "error" => "error_message" }
    }
  }
}
