config:
  pipeline:
    inputs:
      - name: tail
        alias: coredns
        path: /var/log/containers/coredns*.log
        tag: coredns
        skip_empty_lines: true

    outputs:
      - name: loki
        match: "*"
        host: "loki-distributor.loki.svc.cluster.local"
        tenant_id: test
        auto_kubernetes_labels: true
