loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: "${aws_region}"
      bucketnames: ${chunk_bucket_name} # Your actual S3 bucket name, for example, loki-aws-dev-chunks
      s3forcepathstyle: false
  ingester:
    chunk_encoding: snappy
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
    ingestion_rate_mb: 200
    per_stream_rate_limit: 150MB
  compactor:
    retention_enabled: true
    delete_request_store: s3
  ruler:
    enable_api: true
    storage:
      type: s3
      s3:
        region: ${aws_region}
        bucketnames: "${ruler_bucket_name}"
        s3forcepathstyle: false
      alertmanager_url: "${alert_manager_url}" # The URL of the Alertmanager to send alerts (Prometheus, Mimir, etc.)

  querier:
    max_concurrent: 4

  storage:
    type: s3
    bucketNames:
      chunks: "${chunk_bucket_name}"
      ruler: "${ruler_bucket_name}"
      # admin: "<Insert s3 bucket name>" # Your actual S3 bucket name (loki-aws-dev-admin) - GEL customers only
    s3:
      region: "${aws_region}"
      #insecure: false
      # s3forcepathstyle: false

serviceAccount:
  create: true
  annotations:
    "eks.amazonaws.com/role-arn": "${iam_role_arn}" # The service role you created

deploymentMode: Distributed

ingester:
  replicas: 3
  zoneAwareReplication: # This should be enabled for a prod deployment
    enabled: false

querier:
  replicas: 20
  maxUnavailable: 2

queryFrontend:
  replicas: 2
  maxUnavailable: 1

queryScheduler:
  replicas: 2

distributor:
  replicas: 3
  maxUnavailable: 2
compactor:
  replicas: 1

indexGateway:
  replicas: 2
  maxUnavailable: 1

ruler:
  replicas: 1
  maxUnavailable: 1


# This exposes the Loki gateway so it can be written to and queried externaly
# gateway:
#   service:
#     type: LoadBalancer
#   basicAuth:
#     enabled: true
#     existingSecret: loki-basic-auth

# However in our cluster it doesn't need to be accessible from outside, and if we want the UI to be
# later we can add dex auth in front of it with the same oauth2 proxy that prometheus and alertmanager
# have
gateway:
  enabled: false

# Since we are using basic auth, we need to pass the username and password to the canary
# lokiCanary:
#   extraArgs:
#     - -pass=$(LOKI_PASS)
#     - -user=$(LOKI_USER)
#   extraEnv:
#     - name: LOKI_PASS
#       valueFrom:
#         secretKeyRef:
#           name: canary-basic-auth
#           key: password
#     - name: LOKI_USER
#       valueFrom:
#         secretKeyRef:
#           name: canary-basic-auth
#           key: username

# Enable minio for storage
minio:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0
