module "smokey_network_config" {
  source          = "../../modules/task-network-config"
  subnets         = local.private_subnets
  security_groups = [aws_security_group.smokey.id]
}

module "smokey_container_definition" {
  source     = "../../modules/container-definition"
  aws_region = data.aws_region.current.name
  environment_variables = {
    ENVIRONMENT        = var.govuk_environment
    GOVUK_APP_DOMAIN   = local.workspace_external_domain
    GOVUK_WEBSITE_ROOT = local.public_entry_url
    # TODO: This should be autogenerated. Add to signon bootstrap task.
    SIGNON_EMAIL = "signon@alphagov.co.uk" # For historical reasons
  }
  splunk_url_secret_arn   = local.defaults.splunk_url_secret_arn
  splunk_token_secret_arn = local.defaults.splunk_token_secret_arn
  splunk_index            = local.defaults.splunk_index
  splunk_sourcetype       = local.defaults.splunk_sourcetype
  secrets_from_arns = {
    # TODO: These can be autogenerated.
    AUTH_USERNAME = data.aws_secretsmanager_secret.smokey_auth_username.arn
    AUTH_PASSWORD = data.aws_secretsmanager_secret.smokey_auth_password.arn
    # TODO: This should be autogenerated. Add to signon bootstrap task.
    SIGNON_PASSWORD = data.aws_secretsmanager_secret.smokey_signon_password.arn
  }
  ports = []
}

# TODO: can we remove the v2?
module "smokey_task_definition" {
  source                = "../../modules/task-definition"
  container_definitions = [module.smokey_container_definition.json_format]
  cpu                   = 512
  execution_role_arn    = aws_iam_role.execution.arn
  family                = "smokey"
  memory                = 1024
  task_role_arn         = aws_iam_role.task.arn
}
