# This reusable action exists only to reduce toil by representing GOV.UK's
# global config for rhysd/actionlint in a single place so we don't have to
# change it in N repos every time we update.
name: Run actionlint
description: Lint GitHub Actions YAML files with rhysd/actionlint.
runs:
  using: composite
  steps:
    - id: install
      shell: bash
      env:
        ACTIONLINT_SHA: be0549f3c56c3bc347c94e43622466084fafc61d  # v1.7.7
      run: bash <(curl "https://raw.githubusercontent.com/rhysd/actionlint/$ACTIONLINT_SHA/scripts/download-actionlint.bash")
    - name: Run actionlint
      shell: bash
      env:
        ACTIONLINT: '${{ steps.install.outputs.executable }}'
      run: |
        cat <<'EOF' >actionlint-matcher.json
          {"problemMatcher": [{
            "owner": "actionlint",
            "pattern": [{
              "regexp": "^(.+?):(\\d+):(\\d+): (.+?) \\[(.+?)\\]$",
              "file": 1, "line": 2, "column": 3, "message": 4, "code": 5
            }]
          }]}
        EOF
        echo "::add-matcher::actionlint-matcher.json"
        # TODO: move non-global ignores inline or to in-tree actionlint.yml once
        #       https://www.github.com/rhysd/actionlint/issues/237 and/or
        #       https://www.github.com/rhysd/actionlint/issues/217 is fixed.
        # TODO: remove -ignore "property .runner. is not defined" once
        #       https://www.github.com/rhysd/actionlint/issues/77 is fixed.
        "$ACTIONLINT" -no-color \
          -ignore "property .runner. is not defined" \
          -ignore "property .repository_visibility. is not defined"
