name: Lint GitHub Actions
on:
  push:
    paths: ['.github/workflows/**', '.github/actions/**', '.github/actionlint.yml']
jobs:
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
      - uses: alphagov/govuk-infrastructure/.github/actions/actionlint@788b98389ac2003202dc421f4ccd187ad85cda17 # main
