name: Build and publish clamav image to ECR

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
        default: 'main'

  push:
    branches:
      - main
    paths:
      - "images/clamav/**"
  
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-and-push-image:
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-image.yml@main
    with:
      gitRef: ${{ inputs.gitRef || github.ref }}
      ecrRepositoryName: clamav
      dockerfilePath: images/clamav/Dockerfile
    permissions:
      id-token: write
      contents: read
