name: Build image and deploy

on:
  workflow_call:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
        default: 'main'
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'integration'
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      WEBHOOK_TOKEN:
        required: true
      WEBHOOK_URL:
        required: true
      GH_TOKEN:
        required: true

jobs:
  build-image:
    name: Build and push image
    uses: ./.github/workflows/build-and-push-image.yaml
    with:
      gitRef: ${{ inputs.gitRef }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  trigger-deploy:
    name: Trigger deploy to ${{ inputs.environment }}
    needs: build-image
    uses: ./.github/workflows/deploy.yaml
    with:
      imageTag: ${{ needs.build-image.outputs.imageTag }}
      environment: ${{ inputs.environment }}
    secrets:
      WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
