name: Build and publish toolbox image to ECR

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
        default: 'main'

  push:
    branches:
      - main
    paths:
      - "images/toolbox/Dockerfile"
  
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-and-push-image:
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-image-oidc.yml@main
    with:
      gitRef: ${{ inputs.gitRef || github.ref }}
      ecrRepositoryName: toolbox
      dockerfilePath: images/toolbox/Dockerfile
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GOVUK_ECR_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GOVUK_ECR_SECRET_ACCESS_KEY }}
