# USAGE
# -----
#
# on:
#   workflow_dispatch: {}
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - "Jenkinsfile"
#       - ".git**"
#
# jobs:
#   build-publish-image-to-ecr:
#     uses: alphagov/govuk-infrastructure/.github/workflows/ci-ecr.yaml@main
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


# REUSABLE WORKFLOW
# -----------------
name: Build and push image

on:
  workflow_call:
    inputs:
      ecrRepositoryName:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      dockerfilePath:
        required: false
        type: string
        default: Dockerfile
      additionalBuildArgs:
        required: false
        type: string
      gitRef:
        required: false
        type: string
        default: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      imageTag:
        description: "The image tag for the built image"
        value: ${{ jobs.publish.outputs.imageTag }}

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.determine-image-tag.outputs.imageTag }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.gitRef }}

      - name: Determine image tag
        id: determine-image-tag
        run: |
          IMAGE_TAG=$(git rev-parse HEAD)
          echo "imageTag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # TODO: Remove long-lived keys and switch to OIDC once https://github.com/github/roadmap/issues/249 lands.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check for existing image
        id: existing-image
        env:
          ECR_REPOSITORY: ${{ inputs.ecrRepositoryName }}
          IMAGE_TAG: ${{ steps.determine-image-tag.outputs.imageTag }}
        run: |
          check_image_in_ecr() {
            aws ecr describe-images --repository-name="${1}" --image-ids=imageTag="${2}" 2> /dev/null
          }

          if check_image_in_ecr "${ECR_REPOSITORY}" "${IMAGE_TAG}"; then
            echo "Found existing image in ${ECR_REPOSITORY} with the tag ${IMAGE_TAG}. Will not build image again."
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

      - name: Build image
        if: steps.existing-image.outputs.present == 'false'
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecrRepositoryName }}
          IMAGE_TAG: ${{ steps.determine-image-tag.outputs.imageTag }}
          DOCKER_BUILDKIT: "1"
        run: |
          LATEST_GIT_SHA=$(git ls-remote origin HEAD | cut -f 1)
          IMAGE_TAG_ARGS="-t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          if [ "${LATEST_GIT_SHA}" = "${IMAGE_TAG}" ]; then
            IMAGE_TAG_ARGS+=" -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
          fi

          docker build ${IMAGE_TAG_ARGS} ${{ inputs.additionalBuildArgs }} -f ${{ inputs.dockerfilePath }} .

      - name: Push image
        if: steps.build-image.conclusion == 'success'
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecrRepositoryName }}
        run: |
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}" -a
