name: Build and push MongoDB image to ECR

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
        default: main

  push:
    branches:
      - main
    paths:
      - images/mongodb/Dockerfile
  
  schedule:
    - cron: '28 3 * * 1'

jobs:
  build-and-push-image:
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-multiarch-image.yml@af7579152f7630217c9dac2ce5a554a01a0c4f08 # main
    with:
      gitRef: ${{ inputs.gitRef || github.ref }}
      imageName: mongodb
      dockerfilePath: images/mongodb/Dockerfile
    permissions:
      id-token: write
      contents: read
      packages: write
