name: Lint JavaScript

on:
  workflow_call:

jobs:
  lint-javascript:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn run lint:js
