# USAGE
# -----
#
# on:
#   workflow_dispatch: {}
#   push:
#     branches:
#       - main
#   pull_request:
#
# jobs:
#   test:
#     uses: alphagov/govuk-infrastructure/.github/workflows/test-rails.yaml@main
#     with:
#       requiresJavaScript: true
#       requiresMongoDB: true
#       requiresRedis: true
#       requiresMySQL: true
#       mysqlUsername: "test"
#       mysqlPassword: "password"


# REUSABLE WORKFLOW
# -----------------
name: CI

on:
  workflow_call:
    inputs:
      extraSystemDependencies:
        description: 'Install additional system dependencies'
        required: false
        default: ''
        type: string

jobs:
  cache-dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

  lint-ruby:
    name: Lint Ruby
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  security-analysis-ruby:
    name: Security Analysis Ruby
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman . --except CheckRenderInline --quiet

  lint-scss:
    name: Lint SCSS
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Run Stylelint
        run: yarn run stylelint app/assets/stylesheets/

  lint-javascript:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Run Standardx
        run: yarn run standardx 'app/assets/javascripts/**/*.js' 'spec/javascripts/**/*.js'

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    needs: cache-dependencies
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-start-period 10s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
      TEST_DATABASE_URL: mysql2://root:root@127.0.0.1:3306/test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Publishing API (for Content Schemas)
        uses: actions/checkout@v3
        with:
          repository: alphagov/publishing-api
          ref: deployed-to-production
          path: vendor/publishing-api

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Install additional system dependencies
        if: ${{ inputs.extraSystemDependencies }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ${{ inputs.extraSystemDependencies }}

      - name: Initialize database
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rake test

  test-javascript:
    name: Test JavaScript
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn run jasmine:ci
