# USAGE
# -----
#
# on:
#   workflow_dispatch:
#     branches:
#       - main
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - "Jenkinsfile"
#       - ".git**"
#
# jobs:
#   deploy-to-eks:
#     uses: alphagov/govuk-infrastructure/.github/workflows/deploy-to-eks.yaml@main
#     secrets:
#       CI_GITHUB_API_TOKEN: ${{ secrets.CI_GITHUB_API_TOKEN }}

# REUSABLE WORKFLOW
# -----------------

name: Deploy to EKS

on:
  workflow_call:
    secrets:
      CI_GITHUB_API_TOKEN:
        required: true

jobs:
  deploy:
    name: Update image tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          GIT_USER_EMAIL: govuk-ci@digital.cabinet-office.gov.uk
          GIT_USER_NAME: govuk-ci
          GITHUB_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
          ENVIRONMENT: integration
          IMAGE_TAG: ${{ github.sha }}
          APPLICATION: ${{ github.event.repository.name }}
        run: |
          set -eu
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"
          echo "Modifying Helm Charts repo..."
          repo="https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/alphagov/govuk-helm-charts.git"
          branch="main"
          file="charts/argocd-apps/image-tags/${ENVIRONMENT}/${APPLICATION}"
          git clone --depth 1 --branch main "${repo}"
          cd "govuk-helm-charts"
          echo "${IMAGE_TAG}" > "${file}"
          git add $file
          git commit -m "Deploy ${APPLICATION}:${IMAGE_TAG} to ${ENVIRONMENT}"
          REALLY_PUSH_TO_MAIN=1 git push "${repo}" "${branch}"
          echo "Done!"
          echo "::set-output name=image::${APPLICATION}:${IMAGE_TAG}"
