# USAGE
# -----
#
# name: Deploy
#
# on:
#   workflow_dispatch:
#     inputs:
#       gitRef:
#         description: 'Commit, tag or branch name to deploy'
#         required: true
#         type: string
#         default: 'main'
#       environment:
#         description: 'Environment to deploy to'
#         required: true
#         type: choice
#         options:
#         - integration
#         - staging
#         - production
#         default: 'integration'
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - "Jenkinsfile"
#       - ".git**"
#
#
# jobs:
#   trigger-deploy:
#     name: Trigger deploy to ${{ github.event.inputs.environment }}
#     needs: build-and-publish-image
#     uses: alphagov/govuk-infrastructure/.github/workflows/deploy.yaml@main
#     with:
#       imageTag: ${{ needs.build-and-publish-image.outputs.imageTag }}
#       workflowTrigger: ${{ github.event_name }}
#       environment: ${{ github.event.inputs.environment }}
#     secrets:
#       GOVUK_CI_GITHUB_API_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}


#
# REUSABLE WORKFLOW
# -----------------

name: Deploy

on:
  workflow_call:
    inputs:
      imageTag:
        description: 'An image tag to deploy'
        required: false
        default: ${{ github.sha }}
        type: string
      workflowTrigger:
        description: 'event which triggered workflow'
        required: true
        default: "push"
        type: string
      appName:
        description: 'Name of the app being deployed'
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'integration'
        type: string
    secrets:
      GOVUK_CI_GITHUB_API_TOKEN:
        required: true

jobs:
  update-image-tag:
    name: Update image tag
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        env:
          ENVIRONMENT: ${{ inputs.environment || 'integration' }}
          IMAGE_TAG: ${{ inputs.imageTag }}
          REPO_NAME: ${{ inputs.appName }}
          MANUAL_DEPLOY: ${{ github.event_name == 'workflow_dispatch' }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run "Update image tag" \
            -R alphagov/govuk-helm-charts \
            -r update-image-tag-workflow \
            -F "image_tag=${IMAGE_TAG}" \
            -F "repo=${REPO_NAME}" \
            -F "environment=${ENVIRONMENT}" \
            -f "manual_deploy=${MANUAL_DEPLOY}"
