---
name: Lint
on: [push]
permissions: {}
jobs:
  superlinter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        show-progress: false
    - uses: super-linter/super-linter/slim@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_BASH: true
        VALIDATE_BASH_EXEC: true
        VALIDATE_DOCKERFILE_HADOLINT: true
        VALIDATE_EDITORCONFIG: true
        VALIDATE_ENV: true
        VALIDATE_GITHUB_ACTIONS: true
        VALIDATE_JSON: true
        VALIDATE_RENOVATE: true
        VALIDATE_TERRAFORM_FMT: true
        VALIDATE_TERRAFORM_TFLINT: true
        VALIDATE_YAML: true
