---
name: Lint
on: [push]
permissions: {}
jobs:
  superlinter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        show-progress: false
    - uses: super-linter/super-linter/slim@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: move non-global ignores inline or to in-tree actionlint.yml once
        #       https://www.github.com/rhysd/actionlint/issues/237 and/or
        #       https://www.github.com/rhysd/actionlint/issues/217 is fixed.
        # TODO: remove -ignore "property .runner. is not defined" once
        #       https://www.github.com/rhysd/actionlint/issues/77 is fixed.
        GITHUB_ACTIONS_COMMAND_ARGS: >
          -ignore "property .runner. is not defined"
          -ignore "property .repository_visibility. is not defined"
        LINTER_RULES_PATH: .
        VALIDATE_BASH: true
        VALIDATE_BASH_EXEC: true
        VALIDATE_DOCKERFILE_HADOLINT: true
        VALIDATE_EDITORCONFIG: true
        VALIDATE_ENV: true
        VALIDATE_GITHUB_ACTIONS: true
        VALIDATE_JSON: true
        VALIDATE_RENOVATE: true
        VALIDATE_TERRAFORM_FMT: true
        VALIDATE_TERRAFORM_TFLINT: true
        VALIDATE_YAML: true
