# USAGE
# -----
#
# on:
#   push:
#     branches:
#       - main
#
# jobs:
#   ci:
#     uses: alphagov/govuk-infrastructure/.github/workflows/release.yaml@main


# REUSABLE WORKFLOW
# -----------------
name: Release

on:
  workflow_call:
    secrets:
      GOVUK_CI_GITHUB_API_TOKEN:
        required: true

jobs:
  release:
     name: Release
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
           fetch-depth: 0

       - name: Create tag
         env:
           GITHUB_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
         run: |
           PREVIOUS_TAG=$(gh release list --exclude-drafts --limit 1 | cut -f 1)

           [[ ${PREVIOUS_TAG} =~ ([^0-9]*)([0-9]+) ]] || { echo "No number found in tag"; exit 1; }
           TAG="${BASH_REMATCH[1]}$(( ${BASH_REMATCH[2]} + 1 ))"

           gh release create ${TAG} -t "${TAG}" -n ""
