name: Run command

on:
  workflow_call:
    inputs:
      checkoutContentSchemas:
        description: 'Checkout the Publishing API repo for content schemas'
        required: false
        default: false
        type: boolean
      extraSystemDependencies:
        description: 'Install additional system dependencies'
        required: false
        default: ''
        type: string
      enableNodeJS:
        description: 'Setup Node'
        required: false
        default: false
        type: boolean
      enableMySQL:
        description: 'Run MySQL'
        required: false
        default: false
        type: boolean
      enablePostgres:
        description: 'Run Postgres'
        required: false
        default: false
        type: boolean
      enableMongoDB:
        description: 'Run MongoDB'
        required: false
        default: false
        type: boolean
      enableElasticsearch:
        description: 'Run Elasticsearch'
        required: false
        default: false
        type: boolean
      enableRedis:
        description: 'Run Redis'
        required: false
        default: false
        type: boolean
      commands:
        description: 'Commands to run'
        required: true
        type: string

jobs:
  run-command:
    name: Run command
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        id: setup-mysql
        if: ${{ inputs.enableMySQL }}
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@composite-actions

      - name: Setup Postrges
        id: setup-postgres
        if: ${{ inputs.enablePostgres }}
        uses: alphagov/govuk-infrastructure/.github/actions/setup-postgres@composite-actions

      - name: Setup MongoDB
        if: ${{ inputs.enableMongoDB }}
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mongodb@composite-actions

      - name: Setup Elasticsearch
        if: ${{ inputs.enableElasticsearch }}
        uses: alphagov/govuk-infrastructure/.github/actions/setup-elasticsearch@composite-actions

      - name: Setup Redis
        if: ${{ inputs.enableRedis }}
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@composite-actions

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Publishing API (for Content Schemas)
        if: ${{ inputs.checkoutContentSchemas }}
        uses: actions/checkout@v3
        with:
          repository: alphagov/publishing-api
          ref: deployed-to-production
          path: vendor/publishing-api

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        if: ${{ inputs.enableNodeJS }}
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@composite-actions

      - name: Install additional system dependencies
        if: ${{ inputs.extraSystemDependencies }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ${{ inputs.extraSystemDependencies }}

      - name: Run commands
        env:
          RAILS_ENV: test
          GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url ||  steps.setup-postgres.outputs.db-url }}
        run: ${{ inputs.commands }}
