name: SNYK security analysis

on:
  workflow_call:
    inputs:
      skip_sca:
        description: 'Skip Software Component Analysis'
        required: false
        default: false
        type: boolean

jobs:
  sast:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: get-date
        run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        id: cache
        with:
          path: /usr/local/bin/snyk*
          key: snyk-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - uses: snyk/actions/setup@master
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Snyk Code Test
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk code test --severity-threshold=high

  sca:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: ${{ ! inputs.skip_sca }}
    steps:
      - uses: actions/checkout@v4

      - id: get-date
        run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        id: cache
        with:
          path: /usr/local/bin/snyk*
          key: snyk-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - uses: snyk/actions/setup@master
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Snyk Supply Chain Test
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --severity-threshold=high --all-projects --detection-depth=1
