name: SNYK security analysis

on:
  workflow_call:

jobs:
  sast:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk code test --severity-threshold=high

  sca:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Snyk Supply Chain Test
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --severity-threshold=high --all-projects --detection-depth=1
