name: SNYK security analysis

on:
  workflow_call:

jobs:
  sast:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          json: true

  sca:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Snyk Supply Chain Test
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --json --severity-threshold=high >> snyk-sca.json
      - name: Archive SCA results
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca-file
          path: snyk-sca.json
