name: Run Stylelint

on:
  workflow_call:
    inputs:
      files:
        description: 'Files(s) or glob(s) to check'
        required: false
        default: 'app/assets/stylesheets/'
        type: string

jobs:
  run-stylelint:
    name: Run Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@788b98389ac2003202dc421f4ccd187ad85cda17 # main

      - name: Run Stylelint
        run: yarn run stylelint ${{ inputs.files }}
