name: Run Stylelint

on:
  workflow_call:
    inputs:
      files:
        description: 'Files(s) or glob(s) to check'
        required: false
        default: 'app/assets/stylesheets/'
        type: string

jobs:
  run-stylelint:
    name: Run Stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Run Stylelint
        run: yarn run stylelint ${{ inputs.files }}
