# Default values for frontend.

govukEnvironment: test
govukDomainExternal: govuk.digital
govukDomainInternal: govuk-internal.digital
clusterDomain: svc.cluster.local

service:
  type: NodePort
  annotations: {}
  port: 80

replicaCount: 1

appImage:
  repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/frontend
  pullPolicy: IfNotPresent
  tag: latest

nginxImage:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

nginxPort: 80
appPort: 3000

resources: {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## See template file for how application conatiner env default value is computed
appDefaultTtl: "1800"
appGovukAppDomain:
appGovukDomainExternal:
appGovukAppName:
appGovukAppType: "rack"
appGovukContentSchemasPath: "/govuk-content-schemas"
appGovukWebsiteRoot:
appPlekServicePublishingApiUri:
appPlekServiceSignonUri:
appPlekServiceContentStoreUri:
appPlekServiceStaticUri:
appRailsEnv: "production"
appAssetHost:
appGovukAssetRoot:

## Extra environment variables to attach to application container
##
# appExtraEnv:
#   - name: hello
#     value: world
