name: Precompile Rails assets
description: 'Precompile assets and cache'
runs:
  using: "composite"
  steps:
    - name: Assets cache
      uses: actions/cache@v3
      with:
        path: |
          public/assets
          tmp/cache/assets/sprockets
        key: ${{ runner.os }}-rails-assets-${{ github.ref }}-${{ hashFiles('app/assets/**/*', '**/Gemfile.lock', '**/yarn.lock', 'config/**/*') }}
        restore-keys: |
          ${{ runner.os }}-rails-assets-${{ github.ref }}

    - name: Precompile Rails assets
      env:
        RAILS_ENV: test
      shell: bash
      run: bundle exec rails assets:precompile

    - name: Remove old compiled assets
      env:
        RAILS_ENV: test
      shell: bash
      run: bundle exec rails assets:clean
