name: Precompile Rails assets
description: 'Precompile assets and cache'
runs:
  using: "composite"
  steps:
    - name: Assets cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: |
          public/assets
          tmp/cache/assets/sprockets
        key: rails-assets-cache-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}

    - name: Precompile assets
      env:
        RAILS_ENV: test
      shell: bash
      run: bundle exec rails assets:precompile
