name: Precompile Rails assets
description: 'Precompile assets and cache'
runs:
  using: "composite"
  steps:
    - name: Assets cache
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        path: |
          public/assets
          tmp/cache/assets/sprockets
        key: rails-assets-cache-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}

    - name: Precompile assets
      env:
        RAILS_ENV: test
      shell: bash
      run: bundle exec rails assets:precompile
